# Generated by Django 4.1.2 on 2022-11-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Novely',
            new_name='New',
        ),
    ]
