# Generated by Django 4.1.2 on 2022-11-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
