# Generated by Django 4.1.3 on 2022-11-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_event_event_date_event_event_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_start_date',
        ),
    ]
